// Run against an already running server; each test uses a fresh isolated browser session.
const {chromium}=require('@playwright/test');
const assert=require('node:assert/strict');const fs=require('fs');
fs.mkdirSync('test-results',{recursive:true});
const base=process.env.TEST_BASE_URL||'http://localhost:3000';
(async()=>{const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||undefined,headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000);const pass=(name,data={})=>console.log(JSON.stringify({pass:name,...data}));
try{
await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('.drift-wall__tile').first().waitFor();await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'test-results/qa-home.png'});assert.equal(await page.locator('.hero-coordinate,.hero-corner').count(),0);pass('home and signature render');
await page.getByRole('button',{name:'Қаз',exact:true}).click();await page.waitForFunction(()=>document.documentElement.lang==='kk');assert.match(await page.locator('.nav-start').evaluate(e=>getComputedStyle(e).fontFamily),/Noto Sans Kazakh/);assert.match(await page.locator('.nav-start').innerText(),/Таңдауды/);pass('Kazakh alphabet uses consistent font');await page.getByRole('button',{name:'Рус',exact:true}).click();
await page.locator('.catalog-drift-wall').scrollIntoViewIfNeeded();await page.locator('.drift-wall').hover();await page.waitForTimeout(700);
const tile=await page.locator('.drift-wall__tile').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,title:e.getAttribute('aria-label'),r:{top:r.top,bottom:r.bottom}}}).find(t=>t.x>80&&t.x<innerWidth-80&&t.y>130&&t.y<innerHeight-80&&document.elementFromPoint(t.x,t.y)?.closest('.drift-wall__tile')));
assert.ok(tile);await page.mouse.click(tile.x,tile.y);await page.getByRole('dialog',{name:'Подробнее',exact:true}).waitFor();pass('physical photo click opens product',{title:tile.title});
await page.getByRole('dialog').getByRole('button',{name:'В корзину',exact:true}).click();await page.getByRole('dialog',{name:'Выберите количество',exact:true}).waitFor();assert.equal(await page.locator('dialog[open]').count(),1);await page.getByRole('spinbutton').fill('1');await page.getByRole('button',{name:'Проверим ваш выбор',exact:true}).click();await page.getByRole('button',{name:'Подтвердить',exact:true}).waitFor();const before=await (await context.request.get(base+'/api/cart')).json();assert.equal(before.cart.items.length,0);pass('quantity proposal leaves cart empty');await page.getByRole('button',{name:'Подтвердить',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'));const added=await(await context.request.get(base+'/api/cart')).json();assert.equal(added.cart.items.length,1);assert.equal(added.cart.items[0].quantity,1);await page.getByRole('link',{name:'Корзина',exact:true}).click();await page.locator('.cart-line').waitFor();await page.reload({waitUntil:'domcontentloaded'});await page.locator('.cart-line').waitFor();pass('confirmed cart survives reload');assert.equal(await page.locator('.cart-bottom-note').count(),0);
await page.locator('.cart-line-actions>button').click();await page.getByRole('button',{name:'Подтвердить',exact:true}).click();await page.locator('.cart-empty').waitFor();pass('confirmed removal');
await page.getByRole('link',{name:'Ассистент',exact:true}).click();await page.getByRole('textbox').fill('Какие условия оплаты и доставки?');await page.getByRole('button',{name:'Отправить',exact:true}).click();await page.locator('.message-assistant').waitFor({timeout:60000});assert.match(await page.locator('.message-assistant').innerText(),/оплат|достав/i);pass('chat response renders with source');
await page.getByRole('button',{name:'Қаз',exact:true}).click();await page.getByRole('textbox').fill('Алматыға жеткізу шарттары қандай?');await page.getByRole('button',{name:'Жіберу',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.message-assistant').length===2,{},{timeout:60000});assert.match(await page.locator('.message-assistant').last().innerText(),/[әғқңөұүһі]/i);pass('Kazakh chat response');
await page.getByRole('button',{name:'Рус',exact:true}).click();await page.getByRole('link',{name:'Каталог',exact:true}).click();await page.locator('.search-field input').fill('515291');await page.locator('.product-card').first().waitFor();await page.waitForFunction(()=>document.querySelectorAll('.product-card').length===1);assert.match(await page.locator('.product-card').innerText(),/Legrand/);pass('catalog SKU search');await page.screenshot({path:'test-results/qa-catalog-desktop.png'});
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);await page.screenshot({path:'test-results/qa-catalog-mobile.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));pass('mobile has no horizontal overflow');assert.deepEqual(errors,[]);pass('no browser runtime errors');
}finally{await page.screenshot({path:'test-results/qa-final.png'}).catch(()=>{});await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
