// Run against an already running server; each test uses a fresh isolated browser session.
const {chromium}=require('@playwright/test');
const assert=require('node:assert/strict');const fs=require('fs');fs.mkdirSync('test-results',{recursive:true});
const base=process.env.TEST_BASE_URL||'http://localhost:3000';
(async()=>{const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||undefined,headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage();page.setDefaultTimeout(25000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const pass=(name,data={})=>console.log(JSON.stringify({pass:name,...data}));try{
await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('.drift-wall__tile').first().waitFor();
await page.locator('input[type=file]').setInputFiles({name:'test-specification.txt',mimeType:'text/plain',buffer:Buffer.from('Артикул;Количество\n200300285_;2\n19281;3\n999999999999;1')});await page.locator('.prompt-bar__chip').waitFor();await page.getByRole('textbox').fill('Разбери спецификацию по строкам. Я проверю результат перед добавлением.');await page.getByRole('button',{name:'Отправить',exact:true}).click();await page.locator('.spec-review-row').first().waitFor({timeout:60000});assert.equal(await page.locator('.spec-review-row').count(),3);const rows=page.locator('.spec-review-row');assert.match(await rows.nth(2).innerText(),/Не найдено/);assert.equal(await rows.nth(2).getByRole('checkbox').isDisabled(),true);assert.equal(await page.getByRole('button',{name:/Проверить выбранные/}).isDisabled(),true);pass('uploaded specification becomes reviewable rows, missing SKU is not invented');
await rows.nth(0).getByRole('checkbox').check();await rows.nth(1).getByRole('checkbox').check();await rows.nth(1).getByRole('spinbutton').fill('2');await page.getByRole('button',{name:/Проверить выбранные/}).click();await page.getByRole('button',{name:'Подтвердить',exact:true}).waitFor();assert.equal((await(await context.request.get(base+'/api/cart')).json()).cart.items.length,0);assert.equal(await page.locator('.proposal-line').count(),2);await page.getByRole('button',{name:'Подтвердить',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'));let cart=(await(await context.request.get(base+'/api/cart')).json()).cart;assert.equal(cart.items.length,2);assert.ok(cart.items.every(i=>i.quantity===2));pass('reviewed batch reaches cart only after confirmation');
await page.getByRole('link',{name:'Корзина',exact:true}).click();await page.locator('.cart-line').first().waitFor();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Скачать подборку',exact:true}).click();const download=await downloadPromise;const text=fs.readFileSync(await download.path(),'utf8');assert.match(text,/Подборка товаров/);assert.match(text,/200300285_/);assert.match(text,/Заказ не оформлен/);pass('downloaded manager brief contains real cart and sourcing caveats');
await page.getByRole('link',{name:'Каталог',exact:true}).click();await page.locator('.product-card').nth(1).waitFor();await page.locator('.compare-button').nth(0).click();await page.locator('.compare-button').nth(1).click();await page.getByRole('button',{name:'Сравнить товары',exact:true}).click();await page.getByRole('dialog',{name:'Сравнение товаров'}).waitFor();const rowCount=await page.locator('.comparison-table tbody tr').count();await page.getByRole('checkbox',{name:'Только отличия'}).check();assert.ok(await page.locator('.comparison-table tbody tr').count()<=rowCount);await page.screenshot({path:'test-results/qa-comparison.png'});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);pass('comparison with differences filter, mobile scrolling and Escape');
await page.getByRole('link',{name:'Ассистент',exact:true}).click();await page.locator('.message-list').waitFor();const css=await page.locator('.conversation-composer').evaluate(e=>({background:getComputedStyle(e).backgroundImage,color:getComputedStyle(e).backgroundColor}));assert.equal(css.background,'none');assert.equal(css.color,'rgba(0, 0, 0, 0)');assert.match(await page.locator('.message-list').evaluate(e=>getComputedStyle(e).backdropFilter),/blur/);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'test-results/qa-glass-mobile.png'});await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'test-results/qa-glass-desktop.png'});pass('frosted chat and transparent composer on desktop and mobile');assert.deepEqual(errors,[]);pass('no client runtime errors');
}finally{await page.screenshot({path:'test-results/qa-new-final.png'}).catch(()=>{});await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
