import test from 'node:test';
import assert from 'node:assert/strict';
import { deflateRawSync } from 'node:zlib';
import sharp from 'sharp';
import ExcelJS from 'exceljs';
import { AttachmentError, parseAttachment, validateOfficeArchive, TEXT_CHARACTERS, isLowInformationImage } from '../src/lib/attachment-parser';
const file=(name:string,bytes:Buffer|string)=>new File([typeof bytes==='string'?bytes:new Uint8Array(bytes)],name);
function pdf(pages:number,content='Readable specification'){
 const objects=['<< /Type /Catalog /Pages 2 0 R >>',`<< /Type /Pages /Count ${pages} /Kids [${Array.from({length:pages},(_,i)=>`${4+i*2} 0 R`).join(' ')}] >>`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];
 for(let i=0;i<pages;i++){const stream=content?`BT /F1 12 Tf 40 700 Td (${content}) Tj ET`:'';objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${5+i*2} 0 R >>`,`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);}
 let data='%PDF-1.4\n';const offsets=[0];objects.forEach((object,i)=>{offsets.push(Buffer.byteLength(data));data+=`${i+1} 0 obj\n${object}\nendobj\n`;});const xref=Buffer.byteLength(data);data+=`xref\n0 ${offsets.length}\n0000000000 65535 f \n`+offsets.slice(1).map(n=>`${String(n).padStart(10,'0')} 00000 n \n`).join('')+`trailer\n<< /Size ${offsets.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(data);
}
test('long upload explicitly reports exact model-context truncation',async()=>{const result=await parseAttachment(file('spec.txt','a'.repeat(17000)+'515291;2'));assert.equal(result.text?.length,TEXT_CHARACTERS);assert.equal(result.truncated,true);assert.match(result.warning!,/16 000/);});
test('invalid UTF-8, empty and unsupported files rejected',async()=>{await assert.rejects(parseAttachment(file('bad.txt',Buffer.from([0xff]))),/UTF-8/);await assert.rejects(parseAttachment(file('empty.txt','')),/Пустой/);await assert.rejects(parseAttachment(file('program.exe','x')),e=>e instanceof AttachmentError&&e.status===415);});
test('signature-only image is rejected; valid image fully decodes',async()=>{await assert.rejects(parseAttachment(file('bad.png',Buffer.from([137,80,78,71,13,10,26,10]))),/повреждено/);const pixels=Buffer.alloc(20*20*3,255);pixels.fill(0,0,20*10*3);const png=await sharp(pixels,{raw:{width:20,height:20,channels:3}}).png().toBuffer();const result=await parseAttachment(file('good.png',png));assert.ok(result.dataUrl?.startsWith('data:image/png;base64,'));await assert.rejects(parseAttachment(file('cut.png',png.subarray(0,png.length-16))),/повреждено/);});
test('compressed image above 16MP is rejected before full decode',async()=>{const png=await sharp({create:{width:4001,height:4000,channels:3,background:'#ffffff'}}).png().toBuffer();assert.ok(png.length<3*1024*1024);await assert.rejects(parseAttachment(file('large.png',png)),/16 мегапикселей/);});
test('PDF scan/empty page cannot masquerade as text through page labels',async()=>{await assert.rejects(parseAttachment(file('blank.pdf',pdf(1,''))),/Не найден читаемый текст/);const result=await parseAttachment(file('pages.pdf',pdf(21)));assert.equal(result.truncated,true);assert.match(result.warning!,/20 из 21/);assert.match(result.text!,/Readable specification/);});
test('XLSX extracts displayed numeric formula result and warns on skipped rows',async()=>{const book=new ExcelJS.Workbook(),sheet=book.addWorksheet('Specification');sheet.addRow(['515291',{formula:'2+2',result:4}]);sheet.getCell('A401').value='19281';const result=await parseAttachment(file('spec.xlsx',Buffer.from(await book.xlsx.writeBuffer())));assert.match(result.text!,/515291\t4/);assert.equal(result.truncated,true);assert.match(result.warning!,/400/);const empty=new ExcelJS.Workbook();empty.addWorksheet('Empty');await assert.rejects(parseAttachment(file('empty.xlsx',Buffer.from(await empty.xlsx.writeBuffer()))),/Не найден/);});
test('Office ZIP cannot hide decompression bomb with false size metadata',()=>{const compressed=deflateRawSync(Buffer.alloc(9*1024*1024));const local=Buffer.alloc(31);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(8,8);local.writeUInt32LE(compressed.length,18);local.writeUInt16LE(1,26);local[30]=120;const central=Buffer.alloc(47);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(8,10);central.writeUInt32LE(compressed.length,20);central.writeUInt32LE(0,24);central.writeUInt16LE(1,28);central[46]=120;const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(1,8);end.writeUInt16LE(1,10);end.writeUInt32LE(central.length,12);end.writeUInt32LE(local.length+compressed.length,16);assert.throws(()=>validateOfficeArchive(Buffer.concat([local,compressed,central,end])));});

test('uniform black, white and gray images ask for a clearer photo before AI',async()=>{for(const background of ['#000000','#ffffff','#aaaaaa']){const png=await sharp({create:{width:320,height:240,channels:3,background}}).png().toBuffer();assert.equal(await isLowInformationImage(png),true);await assert.rejects(parseAttachment(file('blank.png',png)),/не виден товар/);}});
test('small visible object on mostly white background passes conservative blank guard',async()=>{const pixels=Buffer.alloc(200*200*3,255);for(let y=95;y<105;y++)for(let x=95;x<105;x++)pixels.fill(0,(y*200+x)*3,(y*200+x)*3+3);const png=await sharp(pixels,{raw:{width:200,height:200,channels:3}}).png().toBuffer();assert.equal(await isLowInformationImage(png),false);assert.ok((await parseAttachment(file('product.png',png))).dataUrl);});
